### ISSUE TITLE
404pages

### ISSUE THREAD

**Issue by karenyeung** [senlin/so-pinyin-slugs#5]
Hi there!
Thanks for the plugin!!!
I just installed so-pinyin-slugs, new article URL being translated into pinyin, however when visit the page it will become 404. 
May I know what kind of setting I need to change too?

Thanks!

**Comment by senlin** [comment]
Hi Karen, thanks for reporting this.
I actually have not encountered this before; could it be an issue with your permalinks?
I would like to ask you to go to the Permalinks page and save them and then try again to visit the page with the translated slug.

**Comment by karenyeung** [comment]
Hi Piet,

Thanks for your email.

even if I turn on permalink only, the Chinese character link will be a 404 page, do I need to change mode for htaccess for it?

Many thanks!

Karen



On 16 Aug, 2016, at 6:02 pm, Piet Bos <notifications@github.com> wrote:

Hi Karen, thanks for reporting this.
I actually have not encountered this before; could it be an issue with your permalinks?
I would like to ask you to go to the Permalinks page and save them and then try again to visit the page with the translated slug.

**Comment by senlin** [comment]
Hi Karen,

This is very strange. I'm assuming you're running latest version of WP and latest version of the plugin as well?

You say "turn on permalink only", what is your current choice of permalink then? Usually nothing needs to be changed in the `htaccess` file for the plugin to work, because that file will be updated the moment you save the permalinks.
Also the Permalinks structure needs to have Postname in it, otherwise it makes no sense to install the plugin.

Could you give me a URL where this happens so I can see for myself? Better even would be to have access to your site, so I can have a look and see what is happening. 
For this you can make a new Admin login and share the details securely via https://so-wp.com/hire-us/?subject=other.

**Comment by senlin** [comment]
@karenyeung Any news on this? If not, then I will close this "issue".
